In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

def load_mnist(path, kind='train'):
    import os
    import gzip
    import numpy as np

    """Load fashion-MNIST data from `path`"""
    labels_path = os.path.join(path,
                               '%s-labels-idx1-ubyte.gz'
                               % kind)
    images_path = os.path.join(path,
                               '%s-images-idx3-ubyte.gz'
                               % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels

location = r""
X_test, y_test = load_mnist(location, kind='t10k')

X_test = X_test/255

X_train, y_train = load_mnist(location)

X_train = X_train/255

print(np.max(X_test))
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

1.0
(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [2]:
train_mask = np.isin(y_train, [3, 6, 7])
X_train = X_train[train_mask]
y_train = y_train[train_mask]

test_mask = np.isin(y_test, [3, 6, 7])
X_test = X_test[test_mask]
y_test = y_test[test_mask]

print(y_train)
print(y_test)

X_train = np.random.permutation(X_train)
y_train = np.random.permutation(y_train)
X_test = np.random.permutation(X_test)
y_test = np.random.permutation(y_test)

print(y_train)
print(y_test)

[3 7 7 ... 6 7 3]
[6 6 7 ... 3 7 6]
[7 3 6 ... 3 7 3]
[6 7 3 ... 3 6 6]


--------------------------------------------------------------------------------------------

In [ ]:
from sklearn.cluster import DBSCAN